"""Hold the Fee Staircase template to the engine, then publish it with its values.

    uv run --no-project --with openpyxl python scripts/learn/verify_fee_staircase.py            # verify only
    uv run --no-project --with openpyxl python scripts/learn/verify_fee_staircase.py --publish  # verify, then
                                                                                                  # rebuild and recalculate
                                                                                                  # the shipped file

Builds a copy of the template with the golden cases in its Catalogue (the same
cases lib/fees.golden.json pins lib/fees.js to, generated by the Python engine),
recalculates it in LibreOffice, and checks every figure the cases name: the size
tier, the dimensional and billable weight, the fee on each card, the band edge
below, the units the rank curve gives, and each of the four edges' gap per unit.
Then it checks the One listing sheet agrees with its own Catalogue row, and that
the simulation is centred where the arithmetic says it must be.

--publish then rebuilds the shipped file, recalculates it (so a viewer that does
not calculate still shows numbers) and writes scripts/learn/fee-staircase.stamp.json:
the hashes of the rate card it was built from and of the file itself.
scripts/learn/template.test.mjs fails when either has moved without a re-run.

Needs LibreOffice (soffice) on PATH.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

from openpyxl import load_workbook

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fee_staircase_template as tpl  # noqa: E402

ROOT = tpl.ROOT
STAMP = ROOT / "scripts" / "learn" / "fee-staircase.stamp.json"
GOLDEN = json.loads((ROOT / "lib" / "fees.golden.json").read_text())
TOL = 0.00015   # a hundredth of a cent: LibreOffice and JavaScript round an exact half differently

MACRO = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script:module PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "module.dtd">
<script:module xmlns:script="http://openoffice.org/2000/script" script:name="Module1" script:language="StarBasic">
    Sub RecalculateAndSave()
      ThisComponent.calculateAll()
      ThisComponent.store()
      ThisComponent.close(True)
    End Sub
</script:module>"""


def recalc(path: Path, timeout: int = 300) -> None:
    """Open the workbook in a throwaway LibreOffice profile, calculate everything, save in place."""
    env = {**os.environ, "SAL_USE_VCLPLUGIN": "svp"}
    with tempfile.TemporaryDirectory(prefix="hubricon-lo-") as prof:
        url = Path(prof).as_uri()
        subprocess.run(["soffice", "--headless", "--terminate_after_init", f"-env:UserInstallation={url}"],
                       env=env, capture_output=True, timeout=timeout, check=False)
        basic = Path(prof) / "user" / "basic" / "Standard"
        if not basic.exists():
            raise SystemExit("LibreOffice did not create a profile; is soffice installed?")
        (basic / "Module1.xba").write_text(MACRO)
        before = path.stat().st_mtime_ns
        subprocess.run(["soffice", "--headless", "--norestore", f"-env:UserInstallation={url}",
                        "vnd.sun.star.script:Standard.Module1.RecalculateAndSave?language=Basic&location=application",
                        str(path)], env=env, capture_output=True, timeout=timeout, check=True)
        if path.stat().st_mtime_ns == before:
            raise SystemExit("LibreOffice exited without saving: nothing was recalculated (another instance running?)")


DIMS = {"small_standard": (5, 4, 0.5), "large_standard": (10, 8, 4)}
TIER = {"Small standard": "small_standard", "Large standard": "large_standard", "Oversize": "oversize", None: None, "": None}


def cases():
    """Catalogue rows and what each must show. A row is {column letter: value}."""
    out = []
    for c in GOLDEN["detect"]:
        a = c["args"]
        dims = tpl_dims(a["dims"])
        row = {"A": "detect", "C": a["price"], "D": a["category"], "E": a["itemWeightOz"], "J": a["bsr"]}
        if dims:
            row.update(dict(zip("GHI", dims)))
        want = {"M": c["item"]["tier"], "N": c["item"]["billableWeightOz"],
                "AZ": c["item"]["estMonthlyUnits"]}
        kinds = {w["kind"]: w["perUnitLow"] for w in c["want"]}
        for kind, col in (("fee_band_edge", "T"), ("price_band_edge", "U"), ("size_tier_edge", "V"), ("dim_weight_overage", "W")):
            want[col] = kinds.get(kind)
        out.append((f"detect {a}", row, want))
    for c in GOLDEN["fees"]:
        tier, w, price, day, card = c["args"]
        if day < "2026-04-17" or day > "2027-01-14" or (tier == "small_standard" and w > 16):
            continue   # before the surcharge, past the loaded cards, or a weight that is no longer small standard
        col = "P" if card == "peak" or day >= "2026-10-15" else "O"
        row = {"A": "fee", "C": price, "D": "Home & Kitchen", "E": w, **dict(zip("GHI", DIMS[tier]))}
        out.append((f"fee {c['args']}", row, {col: c["want"]}))
    for c in GOLDEN["edges"]:
        tier, w = c["args"]
        row = {"A": "edge", "C": 20, "D": "Home & Kitchen", "E": w, **dict(zip("GHI", DIMS[tier]))}
        out.append((f"edge {c['args']}", row, {"R": c["want"], "M": tier}))
    for c in GOLDEN["tiers"]:
        dims, w = c["args"]
        parsed = tpl_dims(dims)
        row = {"A": "tier", "C": 20, "D": "Home & Kitchen", "E": w}
        if parsed:
            row.update(dict(zip("GHI", parsed)))
        out.append((f"tier {c['args']}", row, {"M": c["want"], "AL": c["dim_weight_oz"]}))
    for c in GOLDEN["units"]:
        bsr, cat = c["args"]
        out.append((f"units {c['args']}", {"A": "units", "C": 20, "D": cat, "J": bsr}, {"AZ": c["want"]}))
    return out


def tpl_dims(s):
    if not s:
        return None
    parts = [float(p) for p in s.replace("inches", "").replace("x", " ").split()]
    return tuple(parts)


def same(got, want, col):
    if col == "M":
        return TIER.get(got, got) == want
    if want is None:
        return got in (None, "")
    if got in (None, ""):
        return False
    return abs(float(got) - float(want)) <= TOL


def verify() -> list[str]:
    rows = cases()
    work = Path(tempfile.mkdtemp(prefix="fee-staircase-")) / "verify.xlsx"
    tpl.build(work, catalogue_rows=[r for _, r, _ in rows])
    recalc(work)
    wb = load_workbook(work, data_only=True)
    cat, one, mc = wb["Catalogue"], wb["One listing"], wb["Ten thousand months"]
    failures = []
    errors = [f"{ws.title}!{c.coordinate}={c.value}" for ws in wb.worksheets for row in ws.iter_rows() for c in row
              if isinstance(c.value, str) and c.value.startswith("#")]
    failures += [f"formula error {e}" for e in errors[:20]]
    for i, (label, _, want) in enumerate(rows):
        r = 7 + i
        for col, w in want.items():
            got = cat[f"{col}{r}"].value
            if not same(got, w, col):
                failures.append(f"{label}: {col}{r} is {got!r}, the engine says {w!r}")
    # The single listing and its catalogue row are the same arithmetic.
    tpl.build(work)   # the published layout: the example on both sheets
    recalc(work)
    wb = load_workbook(work, data_only=True)
    cat, one, mc = wb["Catalogue"], wb["One listing"], wb["Ten thousand months"]
    pairs = [("B24", "M7"), ("B23", "N7"), ("B31", "O7"), ("C31", "P7"), ("B36", "R7"), ("B79", "T7"), ("C79", "X7"),
             ("B72", "AZ7"), ("D78", "AD7"), ("E78", "AE7")]
    for a, b in pairs:
        if one[a].value != cat[b].value and not (isinstance(one[a].value, (int, float)) and abs(one[a].value - (cat[b].value or 0)) < 1e-9):
            failures.append(f"One listing {a}={one[a].value!r} but Catalogue {b}={cat[b].value!r}")
    # The simulation is centred on units × the year's edge: its median must land within 4% of that.
    centre = one["B73"].value * mc["F30"].value
    median = mc["K7"].value
    if not (abs(median - centre) / centre < 0.04):
        failures.append(f"simulation median {median:.0f} is not near units × edge {centre:.0f}")
    if mc["K5"].value != tpl.N_MONTHS:
        failures.append(f"simulation drew {mc['K5'].value} months, not {tpl.N_MONTHS}")
    print(f"{len(rows)} golden cases, {len(pairs)} cross-checks, the simulation's centre: "
          f"{'all hold' if not failures else str(len(failures)) + ' failures'}")
    shutil.rmtree(work.parent, ignore_errors=True)
    return failures


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


if __name__ == "__main__":
    failures = verify()
    for f in failures:
        print("  " + f)
    if failures:
        sys.exit(1)
    if "--publish" in sys.argv:
        out = tpl.build()
        recalc(out)
        STAMP.write_text(json.dumps({
            "file": str(out.relative_to(ROOT)),
            "file_sha256": sha(out),
            "ratecard_sha256": sha(ROOT / "ratecard.json"),
            "verified_on": date.today().isoformat(),
            "golden_cases": len(cases()),
        }, indent=2) + "\n")
        print(f"published {out.relative_to(ROOT)} with its values; stamp written")
