"""The Greats of Commerce, readable in one place (docs/content/series/greats-of-commerce.md §6).

`hubricon-content series-doc` renders every series film, `content/videos/greats-*`, from its own
script.md and facts.json: the hooks and the narration with each figure filled in and its key beside
it, the shot brief under each beat, and the facts table with every source. The unit files are the
truth; the document is regenerated from them and never edited by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

from . import script as scriptmod
from .review import _render_with_keys
from .state import CONTENT_DIR

DOC = CONTENT_DIR.parent / "docs" / "content" / "series" / "greats-of-commerce-scripts.md"


def units(videos: Path | None = None) -> list[str]:
    videos = videos or CONTENT_DIR / "videos"
    return sorted(p.name for p in videos.glob("greats-*") if (p / "script.md").exists())


def _cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(slug: str) -> str:
    d = scriptmod.video_dir(slug)
    if not (d / "facts.json").exists():
        from . import facts as factsmod
        factsmod.write(slug)
    facts = json.loads((d / "facts.json").read_text(encoding="utf-8"))
    hp = d / "history.json"
    history = json.loads(hp.read_text(encoding="utf-8")) if hp.exists() else {}
    sc = scriptmod.parse((d / "script.md").read_text(encoding="utf-8"))
    h = sc["header"]
    secs = scriptmod.estimate_seconds(sc, facts)
    words = scriptmod.word_count(scriptmod.spoken(sc), facts)
    r = lambda t: _render_with_keys(t or "", facts)
    out = [f"## {r(h.get('TITLE'))}", "",
           f"`content/videos/{slug}/` · pillar {h.get('PILLAR')} · tier {h.get('TIER')} · "
           f"{words:,} spoken words · about {secs // 60} min", "",
           f"**Spiky claim.** {r(h.get('SPIKY CLAIM'))}  ",
           f"**Misconception.** {r(h.get('MISCONCEPTION'))}  ",
           f"**Thumbnail.** {r(h.get('THUMBNAIL'))}  ",
           f"**Close.** {r(h.get('CTA'))}", "", "### Hooks", ""]
    out += [f"{i}. {r(sc['hooks'][i])}" for i in sorted(sc["hooks"])]
    out += ["", "### The film", ""]
    for b in sc["beats"]:
        out += [f"**[{b['at'] // 60}:{b['at'] % 60:02d}] {b['name']}**", "", r(b["VO"]), ""]
        if b["VISUAL"] and b["VISUAL"] != "chapter":
            out.append(f"> *Picture.* {r(b['VISUAL'])}  ")
        if b["DATA SOURCE"]:
            out.append(f"> *Data.* {b['DATA SOURCE']}  ")
        if b["CTA"]:
            out.append(f"> *Close.* {r(b['CTA'])}  ")
        out.append("")
    used = set(scriptmod.PLACEHOLDER.findall(json.dumps(sc)))
    out += ["### Facts table", "", "Every figure in the narration, with its source. History first, then the engine's "
            "demo figures the film uses.", "", "| key | value | what it is | source |", "|---|---|---|---|"]
    for k, f in history.items():
        out.append(f"| `{k}` | {_cell(f['value'])} | {_cell(f.get('label', k))} | {_cell(f['source'])} |")
    for k in sorted(used - set(history)):
        if k in facts:
            f = facts[k]
            out.append(f"| `{k}` | {_cell(f['value'])} | {_cell(f.get('label', k))} | {_cell(f.get('source', ''))} |")
    return "\n".join(out) + "\n"


def write(doc: Path = DOC) -> Path:
    slugs = units()
    out = ["# The Greats of Commerce: the scripts", "",
           "Generated by `hubricon-content series-doc` from each film's own `script.md` and facts. "
           "Edit the unit (`content/videos/<slug>/`), not this file; the series bible is "
           "[greats-of-commerce.md](greats-of-commerce.md).", "",
           "Figures are filled in with their key beside them (⟨key⟩). *Picture* lines are the shot-plan "
           "skill's brief, in VISUAL_SPEC.md §14's style names.", ""]
    out += [f"- [{s}](#{s})" for s in slugs] + [""]
    for s in slugs:
        out += [f'<a id="{s}"></a>', "", render(s), "---", ""]
    doc.parent.mkdir(parents=True, exist_ok=True)
    doc.write_text("\n".join(out), encoding="utf-8")
    return doc
