/**
 * The 60-second Teardown's arithmetic. A port of the cold engine's pricing —
 * engine/src/hubricon_engine/cold/{priors,findings,shelf}.py and
 * harvest/amazon.py — over the table that engine exports to /ratecard.json.
 *
 * Runs in the browser (teardown.html) and in the Vercel function (api/quick.js)
 * from the same file, so the number a visitor sees on the page and the number
 * the benchmark is computed from are the same number. lib/fees.test.mjs pins
 * this file to golden values generated by the Python; when one side moves, the
 * test says so.
 *
 * The rules the Python keeps are kept here:
 *   - a per-unit figure is arithmetic off a published card, or it is null;
 *   - a monthly figure is always a bracket, because the rank→units curve is
 *     wrong by a factor of two either way;
 *   - a size tier is never guessed: no dimensions, no tier.
 */

export const UNITS_LOW = 0.5;
export const UNITS_HIGH = 1.5;
export const MAX_SHAVEABLE_OZ = 2.0;
export const MIN_PER_UNIT_USD = 0.08;
export const MAX_ENVELOPE_OVERAGE = 1.35;
export const MIN_DIM_WEIGHT_RATIO = 1.3;
export const FBA_BUCKETS = [0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0];
export const NEAR_EDGE_OZ = 1.0;
export const MIN_CATEGORY_SAMPLE = 30;
export const AXES = ["length", "width", "thickness"];

const isoDay = (d) => (d instanceof Date ? d.toISOString().slice(0, 10) : String(d));

// -- the card in force -------------------------------------------------------------

export function cardFor(rc, today) {
  const day = isoDay(today || new Date());
  for (const [name, c] of Object.entries(rc.fba.cards)) {
    if (c.effective <= day && day <= c.through) return { name, ...c };
  }
  return null;
}

export function cardNamed(rc, name) {
  const c = rc.fba.cards[name];
  return c ? { name, ...c } : null;
}

export function stale(rc, today) {
  if (cardFor(rc, today)) return null;
  const cards = Object.values(rc.fba.cards);
  const day = isoDay(today || new Date());
  if (day < cards[0].effective) return `the FBA rate card starts ${cards[0].effective}`;
  return `the loaded FBA rate cards end ${cards[cards.length - 1].through}; Amazon's next schedule is not loaded yet`;
}

export function priceBand(rc, price) {
  if (price == null || !(price > 0)) return null;
  const [lo, hi] = rc.fba.price_band_edges;
  if (price < lo) return 0;
  if (price <= hi) return 1;
  return 2;
}

export function referralRate(rc, category) {
  const cat = String(category || "").trim().toLowerCase();
  return rc.fba.referral_by_category[cat] ?? rc.fba.referral_default;
}

export function referralFee(rc, price, category) {
  return Math.max(price * referralRate(rc, category), rc.fba.referral_min_usd);
}

function surcharged(rc, fee, today) {
  const day = isoDay(today || new Date());
  const f = day >= rc.fba.fuel_surcharge_from ? fee * (1 + rc.fba.fuel_surcharge) : fee;
  return Math.round(f * 1e4) / 1e4;
}

/** $ per unit to fulfil one of these on `card` (default: the card in force), or null off the card. */
export function fulfilmentFee(rc, tier, weightOz, price, today, card) {
  card = card || cardFor(rc, today);
  const band = priceBand(rc, price);
  if (!card || band == null || weightOz == null || !(weightOz > 0)) return null;
  if (tier === "small_standard") {
    if (weightOz > rc.fba.small_standard_max_oz) return null;
    for (const [edge, fees] of card.small_standard) if (weightOz <= edge) return surcharged(rc, fees[band], today);
    return null;
  }
  if (tier === "large_standard") {
    if (weightOz > rc.fba.large_standard_max_oz) return null;
    for (const [edge, fees] of card.large_standard) if (weightOz <= edge) return surcharged(rc, fees[band], today);
    const steps = Math.ceil((weightOz - 48) / 4);
    return surcharged(rc, card.over_3lb_base[band] + card.over_3lb_per_4oz * steps, today);
  }
  return null;
}

/** The heaviest band edge this unit is above, within its tier; null in the lightest band. */
export function bandEdgeBelow(rc, card, tier, weightOz) {
  if (!weightOz || !card) return null;
  const table = tier === "small_standard" ? card.small_standard : card.large_standard;
  const edges = table.map(([e]) => e);
  if (tier === "large_standard" && weightOz > edges[edges.length - 1]) {
    const steps = Math.ceil((weightOz - 48) / 4);
    return 48 + 4 * (steps - 1);
  }
  const below = edges.filter((e) => e < weightOz);
  return below.length ? below[below.length - 1] : null;
}

// -- the box ---------------------------------------------------------------------

/** "12.4 x 8.1 x 2 inches" | [12.4, 8.1, 2] → [12.4, 8.1, 2] longest first, or null. */
export function parseDims(s) {
  let vals;
  if (Array.isArray(s)) vals = s.map(Number);
  else {
    const m = String(s || "").match(/([\d.]+)\s*[x×by]+\s*([\d.]+)\s*[x×by]+\s*([\d.]+)\s*(cm|centi|in|inch|inches|")?/i);
    if (!m) return null;
    vals = [m[1], m[2], m[3]].map(Number);
    if ((m[4] || "").toLowerCase().startsWith("c")) vals = vals.map((v) => v / 2.54);
  }
  if (vals.length !== 3 || vals.some((v) => !(v > 0))) return null;
  return vals.sort((a, b) => b - a).map((v) => Math.round(v * 100) / 100);
}

/** Cubic inches over the divisor, in ounces — only once the parcel passes a cubic foot. */
export function dimWeightOz(rc, dims) {
  if (!dims) return null;
  const cubic = dims[0] * dims[1] * dims[2];
  if (cubic < rc.fba.dim_weight_min_cuft * 1728) return null;
  return Math.round((cubic / rc.fba.dim_divisor) * 16 * 100) / 100;
}

export function sizeTier(rc, dims, weightOz) {
  if (!dims || weightOz == null) return null;
  const fits = (env) => dims.every((d, i) => d <= env[i]);
  if (weightOz <= rc.fba.small_standard_max_oz && fits(rc.fba.small_standard_envelope_in)) return "small_standard";
  if (weightOz <= rc.fba.large_standard_max_oz && fits(rc.fba.large_standard_envelope_in)) return "large_standard";
  return "oversize";
}

/** What Amazon bills on: the greater of the item weight and the dimensional weight. */
export function billableWeightOz(rc, dims, weightOz) {
  const dw = dimWeightOz(rc, dims);
  if (weightOz == null) return dw;
  return dw != null && dw > weightOz ? dw : weightOz;
}

// -- volume from rank -------------------------------------------------------------

export function estimateUnits(rc, bsr, category) {
  if (!bsr || bsr < 1) return null;
  const u = rc.units_curve;
  const cat = String(category || "").trim().toLowerCase();
  const scale = u.category_scale[cat] ?? u.default_scale;
  const knee = 10 ** (u.a - u.b * Math.log10(u.head_knee));
  const units = bsr >= u.head_knee ? 10 ** (u.a - u.b * Math.log10(bsr)) : knee * (u.head_knee / bsr) ** u.head_exp;
  return Math.round(scale * units * 10) / 10;
}

export function monthlyBracket(perUnitLow, perUnitHigh, units) {
  if (!units) return [0, 0];
  return [Math.round(perUnitLow * units * UNITS_LOW * 100) / 100, Math.round(perUnitHigh * units * UNITS_HIGH * 100) / 100];
}

/** Ounces above the nearest cheaper band edge on the tier-aware ladder (shelf._over_by). */
export function overBy(rc, card, weightOz, dims) {
  if (!weightOz || !(weightOz > 0)) return null;
  const parsed = dims ? (Array.isArray(dims) ? dims : parseDims(dims)) : null;
  const tier = parsed ? sizeTier(rc, parsed, weightOz) : null;
  let edge;
  if (tier === "small_standard" || tier === "large_standard") edge = bandEdgeBelow(rc, card, tier, weightOz);
  else if (tier === "oversize") return null;
  else {
    const s = bandEdgeBelow(rc, card, "small_standard", weightOz);
    const l = bandEdgeBelow(rc, card, "large_standard", weightOz);
    if (weightOz > rc.fba.small_standard_max_oz) edge = l;
    else if (s === l) edge = s;
    else return null;
  }
  return edge == null ? null : Math.round((weightOz - edge) * 100) / 100;
}

// -- one listing, described ---------------------------------------------------------

/** Normalise raw inputs into the Item the detectors read. */
export function describeItem(rc, { price, category, bsr, itemWeightOz, dims }) {
  const parsed = dims ? (Array.isArray(dims) ? dims : parseDims(dims)) : null;
  const itemW = itemWeightOz > 0 ? Number(itemWeightOz) : null;
  const dimW = dimWeightOz(rc, parsed);
  const billable = billableWeightOz(rc, parsed, itemW);
  const tier = sizeTier(rc, parsed, billable);
  const units = estimateUnits(rc, bsr, category);
  return {
    price: price > 0 ? Number(price) : null,
    category: category || null,
    rank: bsr > 0 ? Number(bsr) : null,
    itemWeightOz: itemW,
    dims: parsed,
    dimWeightOz: dimW,
    billableWeightOz: billable,
    tier,
    estMonthlyUnits: units,
    estMonthlyRevenue: units && price > 0 ? Math.round(units * price * 100) / 100 : null,
  };
}

const midPrice = (band) => [9.99, 25.0, 99.0][band];

function priceBandJumpRange(rc, card, tier, weightOz, bandFrom, bandTo, today) {
  if ((tier === "small_standard" || tier === "large_standard") && weightOz) {
    const hi = fulfilmentFee(rc, tier, weightOz, midPrice(bandTo), today, card);
    const lo = fulfilmentFee(rc, tier, weightOz, midPrice(bandFrom), today, card);
    if (hi == null || lo == null) return null;
    const d = Math.round((hi - lo) * 1e4) / 1e4;
    return [d, d];
  }
  const deltas = [];
  for (const table of [card.small_standard, card.large_standard]) for (const [, fees] of table) deltas.push(fees[bandTo] - fees[bandFrom]);
  deltas.push(card.over_3lb_base[bandTo] - card.over_3lb_base[bandFrom]);
  const mult = isoDay(today || new Date()) >= rc.fba.fuel_surcharge_from ? 1 + rc.fba.fuel_surcharge : 1;
  return [Math.round(Math.min(...deltas) * mult * 1e4) / 1e4, Math.round(Math.max(...deltas) * mult * 1e4) / 1e4];
}

function volumeAssumption(item) {
  return item.estMonthlyUnits && item.rank
    ? `about ${Math.round(item.estMonthlyUnits).toLocaleString("en-US")} units a month, estimated from this listing's public sales rank (#${item.rank.toLocaleString("en-US")} in ${item.category}); the monthly range spans half to one and a half times that`
    : "no monthly volume — the per-unit figure is the whole claim";
}

function cardAssumption(card) {
  const which = card.name === "peak" ? "holiday peak " : "";
  return `Amazon's published US FBA ${which}fulfilment fee schedule, ${card.effective} to ${card.through}, including the 3.5% fuel and logistics surcharge`;
}

export function priceBandEdge(rc, card, item, today) {
  const price = item.price;
  if (!price) return null;
  const band = priceBand(rc, price);
  if (band == null || band === 0) return null;
  const edge = rc.fba.price_band_edges[band - 1];
  const below = Math.round((edge - 0.01) * 100) / 100;
  const jump = priceBandJumpRange(rc, card, item.tier, item.billableWeightOz, band - 1, band, today);
  if (!jump) return null;
  const rate = referralRate(rc, item.category);
  const givenUp = (price - below) * (1 - rate);
  const perUnitLow = Math.round((jump[0] - givenUp) * 1e4) / 1e4;
  const perUnitHigh = Math.round((jump[1] - givenUp) * 1e4) / 1e4;
  if (perUnitLow <= MIN_PER_UNIT_USD) return null;
  const exact = jump[0] === jump[1];
  const [lo, hi] = monthlyBracket(perUnitLow, perUnitHigh, item.estMonthlyUnits);
  const assumptions = [cardAssumption(card), `a ${Math.round(rate * 100)}% referral fee, Amazon's published rate for ${item.category || "this category"}`, volumeAssumption(item)];
  if (!exact) assumptions.push("your packed weight is not published, so the fee jump is the range that step takes across Amazon's whole standard-size schedule");
  return {
    kind: "price_band_edge", dollarsLow: lo, dollarsHigh: hi, perUnitLow, perUnitHigh,
    confidence: exact ? 0.9 : 0.8, assumptions,
    evidence: { chart: "net_vs_price", edge, yourPrice: price, targetPrice: below, feeJumpLow: jump[0], feeJumpHigh: jump[1], referralRate: rate, tier: item.tier, weightOz: item.billableWeightOz, breakEvenPrice: Math.round((below + jump[1] / (1 - rate)) * 100) / 100 },
  };
}

export function feeBandEdge(rc, card, item, today) {
  const weight = item.itemWeightOz, price = item.price;
  if (!weight || !price) return null;
  if (item.tier === "oversize") return null;
  const tiers = item.tier === "small_standard" || item.tier === "large_standard" ? [item.tier] : ["small_standard", "large_standard"];
  const edges = tiers.map((t) => bandEdgeBelow(rc, card, t, weight));
  if (edges.some((e) => e == null)) return null;
  if (new Set(edges).size !== 1) return null;
  const edge = edges[0];
  const overBy = Math.round((weight - edge) * 1000) / 1000;
  if (overBy > MAX_SHAVEABLE_OZ) return null;
  const deltas = [];
  for (const t of tiers) {
    const now = fulfilmentFee(rc, t, weight, price, today, card);
    const atEdge = fulfilmentFee(rc, t, edge, price, today, card);
    if (now == null || atEdge == null) continue;
    deltas.push(Math.round((now - atEdge) * 1e4) / 1e4);
  }
  if (!deltas.length) return null;
  const perUnitLow = Math.min(...deltas), perUnitHigh = Math.max(...deltas);
  if (perUnitHigh < MIN_PER_UNIT_USD) return null;
  const [lo, hi] = monthlyBracket(perUnitLow, perUnitHigh, item.estMonthlyUnits);
  const exact = tiers.length === 1;
  const assumptions = [cardAssumption(card), "your listing's published item weight, which is a floor: Amazon bills the packed weight, which adds its own packaging, so the unit is at least this heavy", volumeAssumption(item)];
  if (!exact) assumptions.push("your packed dimensions are not published, so the figure spans both standard size tiers — the smaller number is the safe one");
  return {
    kind: "fee_band_edge", dollarsLow: lo, dollarsHigh: hi, perUnitLow, perUnitHigh,
    confidence: exact ? 0.72 : 0.6, assumptions,
    evidence: { chart: "fee_vs_weight", edge, yourWeightOz: weight, overByOz: overBy, tier: item.tier, tiersConsidered: tiers, price },
  };
}

export function dimWeightOverage(rc, card, item, today) {
  const dimW = item.dimWeightOz, itemW = item.itemWeightOz, price = item.price, tier = item.tier;
  if (!dimW || !itemW || !price || (tier !== "small_standard" && tier !== "large_standard")) return null;
  if (dimW < itemW * MIN_DIM_WEIGHT_RATIO) return null;
  const billed = fulfilmentFee(rc, tier, dimW, price, today, card);
  const onWeight = fulfilmentFee(rc, tier, itemW, price, today, card);
  if (billed == null || onWeight == null) return null;
  const perUnit = Math.round((billed - onWeight) * 1e4) / 1e4;
  if (perUnit < MIN_PER_UNIT_USD) return null;
  const [lo, hi] = monthlyBracket(perUnit, perUnit, item.estMonthlyUnits);
  return {
    kind: "dim_weight_overage", dollarsLow: lo, dollarsHigh: hi, perUnitLow: perUnit, perUnitHigh: perUnit, confidence: 0.7,
    assumptions: [cardAssumption(card), `the packed dimensions you entered (${item.dims.join(" × ")} in) are the dimensions Amazon measures`, `dimensional weight at the standard divisor of ${rc.fba.dim_divisor}, which applies once a parcel passes a cubic foot`, volumeAssumption(item)],
    evidence: { chart: "fee_vs_weight", itemWeightOz: itemW, dimWeightOz: dimW, dims: item.dims, tier, cubicIn: Math.round(item.dims[0] * item.dims[1] * item.dims[2] * 10) / 10, price, edge: null, yourWeightOz: dimW },
  };
}

export function sizeTierEdge(rc, card, item, today) {
  const dims = item.dims, weight = item.billableWeightOz, price = item.price;
  if (!dims || !weight || !price) return null;
  if (weight > rc.fba.small_standard_max_oz || item.tier !== "large_standard") return null;
  const env = rc.fba.small_standard_envelope_in;
  const over = dims.map((d, i) => [i, d, env[i]]).filter(([, d, lim]) => d > lim);
  if (over.length !== 1) return null;
  const [axis, actual, limit] = over[0];
  if (actual / limit > MAX_ENVELOPE_OVERAGE) return null;
  const large = fulfilmentFee(rc, "large_standard", weight, price, today, card);
  const small = fulfilmentFee(rc, "small_standard", weight, price, today, card);
  if (large == null || small == null) return null;
  const perUnit = Math.round((large - small) * 1e4) / 1e4;
  if (perUnit < MIN_PER_UNIT_USD) return null;
  const [lo, hi] = monthlyBracket(perUnit, perUnit, item.estMonthlyUnits);
  return {
    kind: "size_tier_edge", dollarsLow: lo, dollarsHigh: hi, perUnitLow: perUnit, perUnitHigh: perUnit, confidence: 0.78,
    assumptions: [cardAssumption(card), "the dimensions you entered are the packed dimensions Amazon measures", `Amazon's small-standard envelope: ${env[0]} × ${env[1]} × ${env[2]} in and ${rc.fba.small_standard_max_oz} oz`, volumeAssumption(item)],
    evidence: { chart: "size_tier", axis: AXES[axis], actualIn: actual, limitIn: limit, overByIn: Math.round((actual - limit) * 1000) / 1000, dims, weightOz: weight, smallFee: small, largeFee: large, price },
  };
}

export function detect(rc, item, today) {
  const card = cardFor(rc, today);
  if (!card) return [];
  const out = [];
  for (const d of [priceBandEdge, feeBandEdge, dimWeightOverage, sizeTierEdge]) {
    const f = d(rc, card, item, today);
    if (f) out.push(f);
  }
  out.sort((a, b) => b.confidence * ((b.dollarsLow + b.dollarsHigh) / 2 || b.perUnitHigh) - a.confidence * ((a.dollarsLow + a.dollarsHigh) / 2 || a.perUnitHigh));
  return out;
}

// -- unit economics ----------------------------------------------------------------

/**
 * One unit through Amazon's two published fees, on the card in force and on the
 * peak card, then — only if the seller gives a landed cost — the numbers no free
 * calculator derives: the break-even ACoS and the price floor.
 */
export function unitEconomics(rc, item, cogs, today) {
  const price = item.price;
  if (!price) return null;
  const rate = referralRate(rc, item.category);
  const referral = Math.round(referralFee(rc, price, item.category) * 100) / 100;
  const card = cardFor(rc, today);
  const peak = cardNamed(rc, "peak");
  const tierKnown = item.tier === "small_standard" || item.tier === "large_standard";
  const fee = tierKnown && card ? fulfilmentFee(rc, item.tier, item.billableWeightOz, price, today, card) : null;
  const feePeak = tierKnown && peak ? fulfilmentFee(rc, item.tier, item.billableWeightOz, price, today, peak) : null;
  const keep = fee != null ? Math.round((price - referral - fee) * 100) / 100 : null;
  const out = {
    price, referralRate: rate, referral, card: card ? card.name : null, fee, feePeak,
    peakDelta: fee != null && feePeak != null ? Math.round((feePeak - fee) * 100) / 100 : null,
    keep, keepPct: keep != null ? keep / price : null,
    amazonTakePct: keep != null ? (price - keep) / price : null,
    cogs: cogs > 0 ? Number(cogs) : null,
  };
  if (out.cogs != null && fee != null) {
    const contribution = Math.round((keep - out.cogs) * 100) / 100;
    out.contribution = contribution;
    out.breakEvenAcos = contribution / price;              // ads break even on profit, not revenue
    out.priceFloor = Math.round(((out.cogs + fee) / (1 - rate)) * 100) / 100;
    out.priceFloorPeak = feePeak != null ? Math.round(((out.cogs + feePeak) / (1 - rate)) * 100) / 100 : null;
  }
  if (out.peakDelta != null && out.peakDelta > 0) {
    out.priceToHoldMargin = Math.round((price + out.peakDelta / (1 - rate)) * 100) / 100;
    if (item.estMonthlyUnits) {
      // The peak window is three months; the bracket is the volume curve's.
      out.peakWindowLow = Math.round(out.peakDelta * item.estMonthlyUnits * UNITS_LOW * 3);
      out.peakWindowHigh = Math.round(out.peakDelta * item.estMonthlyUnits * UNITS_HIGH * 3);
    }
  }
  return out;
}

// -- ten thousand months -----------------------------------------------------------

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function gaussian(rand) {
  let u = 0, v = 0;
  while (u === 0) u = rand();
  while (v === 0) v = rand();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

/**
 * Monthly profit on one listing, simulated. The only large uncertainty is the
 * volume: the rank→units curve is wrong by a factor of two either way, which
 * is a lognormal with sigma = ln 2 / 1.645 (so 5% and 95% land at half and
 * double the estimate). The landed cost drifts ±10% for freight and FX. Fees
 * are the published card and do not move.
 */
export function simulateMonthly({ units, price, referral, fee, cogs, n = 10000, seed = 7, sigma = Math.log(2) / 1.645 }) {
  if (!units || !price || fee == null || cogs == null) return null;
  const rand = mulberry32(seed);
  const profits = new Float64Array(n);
  const mu = Math.log(units);
  for (let i = 0; i < n; i++) {
    const u = Math.exp(mu + sigma * gaussian(rand));
    const c = cogs * (0.9 + 0.2 * rand());
    profits[i] = u * (price - referral - fee - c);
  }
  const sorted = Array.from(profits).sort((a, b) => a - b);
  const q = (p) => sorted[Math.min(n - 1, Math.floor(p * n))];
  const mean = sorted.reduce((s, x) => s + x, 0) / n;
  const lo = sorted[0], hi = sorted[n - 1];
  const bins = 28, width = (hi - lo) / bins || 1;
  const hist = Array.from({ length: bins }, (_, i) => ({ lo: lo + i * width, hi: lo + (i + 1) * width, count: 0 }));
  for (const x of sorted) hist[Math.min(bins - 1, Math.floor((x - lo) / width))].count++;
  return { n, p5: q(0.05), p10: q(0.1), p50: q(0.5), p90: q(0.9), p95: q(0.95), mean, pLoss: sorted.filter((x) => x < 0).length / n, hist };
}

// -- the category around it --------------------------------------------------------

/** shelf.benchmark for Amazon rows: how far every listing we have weighed sits above its band edge. */
export function benchmark(rc, card, rows, category, yourWeightOz, yourDims) {
  if (!category) return null;
  const wanted = String(category).trim().toLowerCase();
  const pool = rows.filter((r) => (r.platform || "amazon") === "amazon" && String(r.category || "").trim().toLowerCase() === wanted && r.weight_oz);
  const measured = pool.map((r) => overBy(rc, card, Number(r.weight_oz), r.dims)).filter((w) => w != null);
  if (measured.length < MIN_CATEGORY_SAMPLE) return null;
  const edges = FBA_BUCKETS;
  const buckets = edges.map((lo, i) => [lo, i + 1 < edges.length ? edges[i + 1] : 999, 0]);
  for (const w of measured) {
    const i = buckets.findIndex(([lo, hi]) => w >= lo && w < hi);
    if (i >= 0) buckets[i][2]++;
  }
  const near = measured.filter((w) => w <= NEAR_EDGE_OZ).length;
  return { category, measured: measured.length, near, share: near / measured.length, buckets, yourOverBy: overBy(rc, card, yourWeightOz, yourDims) };
}

// -- the whole result, from inputs ---------------------------------------------------

/** Everything /teardown shows, computed from the typed inputs; the email is built from this, never from client text. */
export function analyse(rc, inputs, today) {
  const item = describeItem(rc, inputs);
  const found = detect(rc, item, today);
  const u = unitEconomics(rc, item, inputs.cogs, today);
  const sim = u && u.contribution != null && item.estMonthlyUnits
    ? simulateMonthly({ units: item.estMonthlyUnits, price: u.price, referral: u.referral, fee: u.fee, cogs: u.cogs })
    : null;
  return { item, u, found, sim };
}

/** The inputs as the page encodes them in its URL hash, so a link reproduces the result. */
export function resultHash(inputs) {
  const p = new URLSearchParams();
  if (inputs.asin) p.set("a", inputs.asin);
  p.set("p", inputs.price); p.set("w", inputs.itemWeightOz);
  if (inputs.dims) p.set("d", (Array.isArray(inputs.dims) ? inputs.dims : parseDims(inputs.dims) || []).join("x"));
  if (inputs.category) p.set("c", inputs.category);
  if (inputs.bsr) p.set("r", inputs.bsr);
  if (inputs.cogs) p.set("k", inputs.cogs);
  return "#" + p.toString();
}

// -- Shopify: the carrier card, Shopify Payments, the anchor gap ------------------------
//
// The Shopify lane has no size tiers and no rank. What is public is the shipping
// weight Shopify hands the carrier, the price and its compare-at, and the two
// published cards: USPS Ground Advantage commercial rates by zone (priors.py,
// exported in the rate card) and Shopify Payments' plan rates. Orders a month
// are the merchant's own number, typed, so figures built on them are not
// bracketed the way a rank estimate is — and the page says which is which.

export const MAX_SHAVEABLE_CARRIER_OZ = 3.0;
export const MIN_DISCOUNT_SHARE = 0.10;
export const CATALOGUE_DISCOUNT_SHARE = 0.5;

/** [band edge below, ounces above it], or null under a pound (the rate is flat there). */
export function shippingCliff(rc, weightOz) {
  const edges = rc.carrier.band_edges_oz;
  if (!weightOz || weightOz <= edges[0]) return null;
  const below = Math.max(...edges.filter((e) => e < weightOz));
  return [below, Math.round((weightOz - below) * 1000) / 1000];
}

/** [what it would pay under the edge, what it pays now]: over a pound bills at the next whole pound. */
export function bandNames(edgeOz) {
  const lb = Math.floor(edgeOz / 16);
  return [lb === 1 ? "under a pound" : `${lb} lb`, `${lb + 1} lb`];
}

/** [what it pays now, what it would pay under the edge] across zones 1–8, or null off the card. */
export function carrierRows(rc, edgeOz) {
  const g = rc.carrier.ground_commercial;
  const now = g[String(edgeOz + 16)];
  const under = g[String(edgeOz === 16 ? 0 : edgeOz)];
  return now && under ? [now, under] : null;
}

/** edge oz → [saving per parcel in the nearest zone, in the farthest]; derived, so the card stays the one place a figure lives. */
export function carrierSteps(rc) {
  const out = {};
  for (const k of Object.keys(rc.carrier.ground_commercial)) {
    const e = Number(k);
    if (e < 16) continue;
    const rows = carrierRows(rc, e);
    if (!rows) continue;
    const steps = rows[0].map((a, i) => Math.round((a - rows[1][i]) * 100) / 100);
    out[e] = [Math.min(...steps), Math.max(...steps)];
  }
  return out;
}

/** The row a parcel bills at: flat under a pound, then the whole pound above it. null past the loaded rows. */
export function carrierCostByZone(rc, weightOz) {
  if (!weightOz || !(weightOz > 0)) return null;
  const g = rc.carrier.ground_commercial;
  const key = weightOz < 16 ? "0" : weightOz === 16 ? "16" : String(Math.ceil(weightOz / 16) * 16);
  return g[key] || null;
}

export function paymentsFee(rc, plan, amount) {
  if (amount == null || !(amount > 0)) return null;
  const p = rc.shopify.payments[String(plan || rc.shopify.default_plan).toLowerCase()] || rc.shopify.payments[rc.shopify.default_plan];
  return Math.round((amount * p.rate + p.fixed) * 1e4) / 1e4;
}

export function describeShopifyItem(rc, { price, compareAtPrice, weightOz, orders, units }) {
  const w = weightOz > 0 ? Number(weightOz) : null;
  const perOrder = units > 0 ? Number(units) : 1;
  const monthlyUnits = orders > 0 ? Number(orders) * perOrder : null;
  return {
    price: price > 0 ? Number(price) : null,
    compareAtPrice: compareAtPrice > 0 ? Number(compareAtPrice) : null,
    itemWeightOz: w, billableWeightOz: w, dims: null, tier: null,
    orders: orders > 0 ? Number(orders) : null, unitsPerOrder: perOrder,
    estMonthlyUnits: monthlyUnits, volumeTyped: Boolean(monthlyUnits),
  };
}

function shopifyVolumeAssumption(item) {
  return item.volumeTyped
    ? `${Math.round(item.orders).toLocaleString("en-US")} orders a month of ${item.unitsPerOrder} unit${item.unitsPerOrder === 1 ? "" : "s"}, as you typed them — not an estimate`
    : "no monthly volume — the per-parcel figure is the whole claim";
}

/** findings.carrier_band_edge: a parcel over a pound, priced off the USPS card as a range across zones. */
export function carrierBandEdge(rc, item) {
  const weight = item.billableWeightOz;
  if (!weight) return null;
  const cliff = shippingCliff(rc, weight);
  if (!cliff) return null;
  const [edge, overBy] = cliff;
  if (overBy > MAX_SHAVEABLE_CARRIER_OZ) return null;
  const [below, above] = bandNames(edge);
  const priced = carrierSteps(rc)[edge] || null;
  const [perUnitLow, perUnitHigh] = priced || [0, 0];
  const [lo, hi] = monthlyBracket(perUnitLow, perUnitHigh, item.volumeTyped ? null : item.estMonthlyUnits);
  const typedLow = item.volumeTyped ? Math.round(perUnitLow * item.orders * 100) / 100 : null;
  const typedHigh = item.volumeTyped ? Math.round(perUnitHigh * item.orders * 100) / 100 : null;
  const assumptions = [
    `the shipping weight set on your own product (${weight} oz) — the one Shopify hands the carrier at checkout, so it is what gets billed rather than an estimate of it; a carrier still bills the greater of that and dimensional weight`,
    `USPS rounds anything over ${edge} oz up to ${above}, so trimming ${overBy} oz moves every parcel to the ${below} rate`,
  ];
  if (priced) assumptions.push(rc.carrier.source, `a range across zones 1 to 8, because your zone mix is not public: $${perUnitLow.toFixed(2)} a parcel to the nearest zones and $${perUnitHigh.toFixed(2)} to the farthest`);
  else assumptions.push("no rate card row for this weight, so this finding carries no dollar figure");
  assumptions.push(shopifyVolumeAssumption(item));
  return {
    kind: "carrier_band_edge", dollarsLow: lo, dollarsHigh: hi, perUnitLow, perUnitHigh,
    monthlyTypedLow: typedLow, monthlyTypedHigh: typedHigh,
    confidence: priced ? 0.74 : 0.55, assumptions,
    evidence: { chart: "carrier_bands", edge, yourWeightOz: weight, overByOz: overBy, bandBelow: below, bandAbove: above, price: item.price, rateCard: priced ? rc.carrier.source : null, rows: carrierRows(rc, edge) },
  };
}

/**
 * findings.permanent_discount without the history it needs to say "permanent":
 * the gap between a product's price and its own compare-at, per unit. With the
 * catalogue's discount share known (the live /products.json answered) the
 * engine's policy gate applies; unknown, the gap is reported as a gap and the
 * page says what would make it a finding.
 */
export function anchorGap(item, catalogueShare) {
  const price = item.price, anchor = item.compareAtPrice;
  if (!price || !anchor || anchor <= price) return null;
  const share = Math.round(((anchor - price) / anchor) * 1e4) / 1e4;
  if (share < MIN_DISCOUNT_SHARE) return null;
  if (catalogueShare != null && catalogueShare < CATALOGUE_DISCOUNT_SHARE) return null;
  const perUnit = Math.round((anchor - price) * 100) / 100;
  if (perUnit < MIN_PER_UNIT_USD) return null;
  const [lo, hi] = monthlyBracket(perUnit, perUnit, item.volumeTyped ? null : item.estMonthlyUnits);
  const typed = item.volumeTyped ? Math.round(perUnit * item.estMonthlyUnits * 100) / 100 : null;
  const assumptions = [
    `your own two published numbers on this product: a compare-at of $${anchor.toFixed(2)} against a price of $${price.toFixed(2)}, so the difference is $${perUnit.toFixed(2)} a unit and is not an estimate`,
    catalogueShare != null
      ? `${Math.round(catalogueShare * 100)}% of your published catalogue is listed below its own compare-at, which is what makes this a price rather than a promotion`
      : "whether this is a promotion or a price depends on how much of the catalogue is marked down, which we could not read; the full Teardown reads all of it",
    "we have not yet watched this price long enough to call it permanent — that takes a fortnight of readings",
  ];
  return {
    kind: "permanent_discount", dollarsLow: lo, dollarsHigh: hi, perUnitLow: perUnit, perUnitHigh: perUnit,
    monthlyTypedLow: typed, monthlyTypedHigh: typed, confidence: 0.55, assumptions,
    evidence: { chart: "net_vs_price", price, compareAt: anchor, discountShare: share, catalogueDiscountShare: catalogueShare ?? null, settled: false },
  };
}

/** shelf.benchmark for Shopify rows: every parcel the crawl has weighed, on the pound boundary. */
export function benchmarkShopify(rc, rows, yourWeightOz) {
  const pool = rows.filter((r) => (r.platform || "amazon") === "shopify" && r.weight_oz);
  const measured = pool.map((r) => shippingCliff(rc, Number(r.weight_oz))).filter(Boolean).map(([, over]) => over);
  if (measured.length < MIN_CATEGORY_SAMPLE) return null;
  const edges = rc.carrier.buckets;
  const buckets = edges.map((lo, i) => [lo, i + 1 < edges.length ? edges[i + 1] : 999, 0]);
  for (const w of measured) {
    const i = buckets.findIndex(([lo, hi]) => w >= lo && w < hi);
    if (i >= 0) buckets[i][2]++;
  }
  const nearOz = rc.carrier.near_edge_oz;
  const near = measured.filter((w) => w <= nearOz).length;
  const mine = shippingCliff(rc, yourWeightOz);
  const stores = new Set(pool.map((r) => r.seller_id).filter(Boolean)).size || null;
  return { category: "Shopify brands", measured: measured.length, near, share: near / measured.length, buckets, yourOverBy: mine ? mine[1] : null, stores };
}

/**
 * One order through Shopify Payments and the carrier, then — with a landed
 * cost — the break-even ROAS and the price floor. Shipping is a range across
 * zones because the merchant's zone mix is not public; the chart shows every
 * zone against what they charge.
 */
export function orderEconomics(rc, item, { plan, shipCharge = 0, thirdParty = false, cogs } = {}) {
  const price = item.price;
  if (!price) return null;
  const units = item.unitsPerOrder || 1;
  const p = rc.shopify.payments[String(plan || rc.shopify.default_plan).toLowerCase()] || rc.shopify.payments[rc.shopify.default_plan];
  const planName = rc.shopify.payments[String(plan || "").toLowerCase()] ? String(plan).toLowerCase() : rc.shopify.default_plan;
  const goods = Math.round(price * units * 100) / 100;
  const charge = Math.max(0, Number(shipCharge) || 0);
  const charged = Math.round((goods + charge) * 100) / 100;
  const surcharge = thirdParty ? (rc.shopify.third_party_surcharge[planName] ?? 0) : 0;
  const payments = Math.round((charged * (p.rate + surcharge) + p.fixed) * 100) / 100;
  const byZone = carrierCostByZone(rc, item.billableWeightOz);
  const shipLow = byZone ? Math.min(...byZone) : null, shipHigh = byZone ? Math.max(...byZone) : null;
  const out = {
    price, units, goods, shipCharge: charge, charged, plan: planName, paymentsRate: p.rate + surcharge, paymentsFixed: p.fixed, payments,
    shipByZone: byZone, shipLow, shipHigh,
    keepLow: shipHigh != null ? Math.round((charged - payments - shipHigh) * 100) / 100 : null,
    keepHigh: shipLow != null ? Math.round((charged - payments - shipLow) * 100) / 100 : null,
    subsidyByZone: byZone ? byZone.map((c) => Math.round((c - charge) * 100) / 100) : null,
    cogs: cogs > 0 ? Number(cogs) : null,
  };
  if (byZone) out.zonesSubsidised = out.subsidyByZone.filter((s) => s > 0).length;
  if (out.cogs != null && byZone) {
    const rate = p.rate + surcharge;
    const cost = out.cogs * units;
    out.contributionLow = Math.round((out.keepLow - cost) * 100) / 100;
    out.contributionHigh = Math.round((out.keepHigh - cost) * 100) / 100;
    out.breakEvenRoasLow = out.contributionHigh > 0 ? Math.round((goods / out.contributionHigh) * 100) / 100 : null;   // nearest zone
    out.breakEvenRoasHigh = out.contributionLow > 0 ? Math.round((goods / out.contributionLow) * 100) / 100 : null;    // farthest zone
    const floor = (ship) => Math.round((((p.fixed + ship + cost) / (1 - rate) - charge) / units) * 100) / 100;
    out.priceFloorLow = floor(shipLow);
    out.priceFloorHigh = floor(shipHigh);
  }
  return out;
}

/** Everything the Shopify side of /teardown shows, from typed inputs. */
export function analyseShopify(rc, inputs) {
  const item = describeShopifyItem(rc, inputs);
  const found = [carrierBandEdge(rc, item), anchorGap(item, inputs.catalogueShare ?? null)].filter(Boolean);
  const econ = orderEconomics(rc, item, { plan: inputs.plan, shipCharge: inputs.shipCharge, thirdParty: inputs.thirdParty, cogs: inputs.cogs });
  return { item, econ, found, sim: null };
}

export function resultHashShopify(inputs) {
  const p = new URLSearchParams({ s: "1" });
  if (inputs.handle) p.set("h", inputs.handle);
  p.set("p", inputs.price); if (inputs.compareAtPrice) p.set("ca", inputs.compareAtPrice);
  p.set("w", inputs.weightOz); if (inputs.units && inputs.units !== 1) p.set("u", inputs.units);
  if (inputs.shipCharge) p.set("sc", inputs.shipCharge); if (inputs.plan) p.set("pl", inputs.plan);
  if (inputs.thirdParty) p.set("tp", "1"); if (inputs.orders) p.set("o", inputs.orders); if (inputs.cogs) p.set("k", inputs.cogs);
  return "#" + p.toString();
}
