// Pins lib/fees.js to values the Python engine produced (lib/fees.golden.json,
// regenerated by the snippet in OPERATIONS.md "The 60-second Teardown"). When a
// number moves on one side and not the other, this is what says so.
//   node --test lib/fees.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import * as fees from "./fees.js";

const rc = JSON.parse(readFileSync(new URL("../ratecard.json", import.meta.url)));
const golden = JSON.parse(readFileSync(new URL("./fees.golden.json", import.meta.url)));
const close = (a, b, tol = 1e-3) => (a == null || b == null ? assert.equal(a, b) : assert.ok(Math.abs(a - b) <= tol, `${a} vs ${b}`));

test("fulfilment fee matches the engine on both cards and outside every window", () => {
  for (const { args: [tier, oz, price, day, cardName], want } of golden.fees) {
    const card = cardName ? fees.cardNamed(rc, cardName) : undefined;
    close(fees.fulfilmentFee(rc, tier, oz, price, day, card), want);
  }
});

test("band edge below matches the engine", () => {
  for (const { args: [tier, oz], want } of golden.edges) {
    const card = fees.cardNamed(rc, "non_peak");
    assert.equal(fees.bandEdgeBelow(rc, card, tier, oz), want);
  }
});

test("size tier and dimensional weight match the engine", () => {
  for (const { args: [dims, oz], want, dims: parsed, dim_weight_oz } of golden.tiers) {
    const p = fees.parseDims(dims);
    assert.deepEqual(p, parsed);
    assert.equal(fees.sizeTier(rc, p, oz), want);
    close(fees.dimWeightOz(rc, p), dim_weight_oz, 0.01);
  }
});

test("rank to units matches the engine's curve", () => {
  for (const { args: [bsr, cat], want } of golden.units) close(fees.estimateUnits(rc, bsr, cat), want, 0.11);
});

test("the detectors find what the engine finds, to the cent", () => {
  for (const { args, item: wantItem, want } of golden.detect) {
    const item = fees.describeItem(rc, args);
    assert.equal(item.tier, wantItem.tier, JSON.stringify(args));
    close(item.billableWeightOz, wantItem.billableWeightOz, 0.01);
    close(item.estMonthlyUnits, wantItem.estMonthlyUnits, 0.11);
    const found = fees.detect(rc, item, "2026-09-08");
    assert.deepEqual(found.map((f) => f.kind), want.map((f) => f.kind), JSON.stringify(args));
    found.forEach((f, i) => {
      close(f.perUnitLow, want[i].perUnitLow, 0.005);
      close(f.perUnitHigh, want[i].perUnitHigh, 0.005);
      close(f.dollarsLow, want[i].dollarsLow, Math.max(0.5, want[i].dollarsLow * 0.002));
      close(f.dollarsHigh, want[i].dollarsHigh, Math.max(0.5, want[i].dollarsHigh * 0.002));
      assert.equal(f.confidence, want[i].confidence);
    });
  }
});

test("unit economics derive the break-even ACoS and the price floor from the card", () => {
  const item = fees.describeItem(rc, { price: 24.99, category: "baby", bsr: 1200, itemWeightOz: 12.0, dims: "12 x 9 x 3 inches" });
  const u = fees.unitEconomics(rc, item, 6.5, "2026-09-08");
  assert.equal(u.card, "non_peak");
  close(u.referral, 24.99 * 0.15, 0.01);
  close(u.fee, 4.20 * 1.035, 0.001);          // large standard 8–12 oz, $10–50 column
  close(u.feePeak, 4.48 * 1.035, 0.001);
  close(u.peakDelta, 0.29, 0.01);
  close(u.keep, 24.99 - u.referral - u.fee, 0.01);
  close(u.contribution, u.keep - 6.5, 0.01);
  close(u.breakEvenAcos, u.contribution / 24.99, 1e-6);
  close(u.priceFloor, (6.5 + u.fee) / 0.85, 0.01);
  close(u.priceToHoldMargin, 24.99 + u.peakDelta / 0.85, 0.01);
});

test("the simulation is reproducible and centred near the point estimate", () => {
  const a = fees.simulateMonthly({ units: 500, price: 24.99, referral: 3.75, fee: 4.35, cogs: 6.5, n: 10000, seed: 7 });
  const b = fees.simulateMonthly({ units: 500, price: 24.99, referral: 3.75, fee: 4.35, cogs: 6.5, n: 10000, seed: 7 });
  assert.equal(a.p50, b.p50);
  const point = 500 * (24.99 - 3.75 - 4.35 - 6.5);
  assert.ok(Math.abs(a.p50 - point) / point < 0.06, `${a.p50} vs ${point}`);
  assert.ok(a.p10 < a.p50 && a.p50 < a.p90 && a.pLoss === 0);
  assert.equal(a.hist.reduce((s, h) => s + h.count, 0), 10000);
});

test("the benchmark refuses a thin category and buckets a fat one", () => {
  const card = fees.cardNamed(rc, "non_peak");
  const thin = Array.from({ length: 10 }, (_, i) => ({ category: "baby", weight_oz: 4 + i * 0.3, dims: "8 x 5 x 1 inches" }));
  assert.equal(fees.benchmark(rc, card, thin, "baby", 4.5, null), null);
  const fat = Array.from({ length: 60 }, (_, i) => ({ category: "baby", weight_oz: 4.1 + (i % 8) * 0.5, dims: "8 x 5 x 1 inches" }));
  const b = fees.benchmark(rc, card, fat, "Baby", 4.6, "8 x 5 x 1 inches");
  assert.equal(b.measured, 60);
  assert.equal(b.buckets.reduce((s, [, , c]) => s + c, 0), 60);
  close(b.yourOverBy, 0.6, 0.001);
  assert.ok(b.share > 0 && b.share <= 1);
});

// -- the Shopify lane ---------------------------------------------------------------

test("the carrier card: cliffs, names, rows and steps match the engine", () => {
  for (const { args: [w], want, names } of golden.carrier.cliff) {
    const c = fees.shippingCliff(rc, w);
    assert.deepEqual(c, want, `cliff at ${w}`);
    if (want) assert.deepEqual(fees.bandNames(c[0]), names);
  }
  for (const [edge, want] of Object.entries(golden.carrier.rows)) assert.deepEqual(fees.carrierRows(rc, Number(edge)), want, `rows at ${edge}`);
  const steps = fees.carrierSteps(rc);
  assert.deepEqual(Object.fromEntries(Object.entries(steps).map(([k, v]) => [k, v])), golden.carrier.steps);
});

test("Shopify Payments matches the engine on every plan", () => {
  for (const { args: [plan, amt], want } of golden.payments) close(fees.paymentsFee(rc, plan, amt), want, 1e-6);
});

test("the Shopify detectors find what the engine finds", () => {
  for (const { name, args, want } of golden.shopify_detect) {
    const item = fees.describeShopifyItem(rc, { price: args.price, compareAtPrice: args.compareAtPrice, weightOz: args.weightOz, orders: null, units: 1 });
    item.estMonthlyUnits = args.estMonthlyUnits;            // the engine estimated it; the tool has it typed
    const found = [fees.carrierBandEdge(rc, item), fees.anchorGap(item, args.catalogueShare)].filter(Boolean);
    assert.deepEqual(found.map((f) => f.kind).sort(), want.map((f) => f.kind).sort(), name);
    for (const w of want) {
      const f = found.find((x) => x.kind === w.kind);
      close(f.perUnitLow, w.perUnitLow, 0.005); close(f.perUnitHigh, w.perUnitHigh, 0.005);
      close(f.dollarsLow, w.dollarsLow, 0.5); close(f.dollarsHigh, w.dollarsHigh, 0.5);
      assert.equal(f.confidence, w.confidence, `${name} ${w.kind} confidence`);
      if (w.edge != null) assert.equal(f.evidence.edge, w.edge);
    }
  }
});

test("the Shopify benchmark matches the engine and refuses a thin pool", () => {
  const g = golden.shopify_bench;
  const b = fees.benchmarkShopify(rc, g.rows, g.your_weight_oz);
  assert.equal(b.measured, g.want.measured); assert.equal(b.near, g.want.near);
  close(b.share, g.want.share, 0.001);
  assert.deepEqual(b.buckets, g.want.buckets);
  close(b.yourOverBy, g.want.your_over_by, 0.001);
  assert.equal(b.stores, 7);
  assert.equal(fees.benchmarkShopify(rc, golden.shopify_bench_thin.rows, 17.2), null);
});

test("order economics: payments on the whole charge, shipping as a zone range, ROAS and floor from cost", () => {
  const item = fees.describeShopifyItem(rc, { price: 32, weightOz: 17.2, orders: 400, units: 1 });
  const e = fees.orderEconomics(rc, item, { plan: "basic", shipCharge: 5.95, cogs: 9 });
  assert.equal(e.charged, 37.95);
  close(e.payments, 37.95 * 0.029 + 0.30, 0.006);
  assert.deepEqual(e.shipByZone, rc.carrier.ground_commercial["32"]);      // 17.2 oz bills at 2 lb
  close(e.shipLow, 7.99, 1e-6); close(e.shipHigh, 12.87, 1e-6);
  close(e.keepHigh, 37.95 - e.payments - 7.99, 0.006); close(e.keepLow, 37.95 - e.payments - 12.87, 0.006);
  assert.equal(e.zonesSubsidised, 8, "a $5.95 flat rate loses money in every zone at 2 lb");
  close(e.contributionHigh, e.keepHigh - 9, 0.006);
  close(e.breakEvenRoasLow, 32 / e.contributionHigh, 0.01);
  // at the floor, the nearest-zone order contributes nothing
  const floorItem = fees.describeShopifyItem(rc, { price: e.priceFloorLow, weightOz: 17.2, orders: 400, units: 1 });
  const atFloor = fees.orderEconomics(rc, floorItem, { plan: "basic", shipCharge: 5.95, cogs: 9 });
  close(atFloor.contributionHigh, 0, 0.02);
  const third = fees.orderEconomics(rc, item, { plan: "basic", shipCharge: 5.95, thirdParty: true, cogs: 9 });
  close(third.paymentsRate, 0.049, 1e-9);
  assert.equal(fees.orderEconomics(rc, fees.describeShopifyItem(rc, { price: 32, weightOz: 60, orders: 1, units: 1 }), {}).shipByZone, null, "past the loaded rows, unpriced");
});

test("analyseShopify assembles the lane and the hash round-trips the typed inputs", () => {
  const r = fees.analyseShopify(rc, { price: 32, compareAtPrice: 45, weightOz: 17.2, orders: 400, units: 1, plan: "grow", shipCharge: 0, cogs: 9, catalogueShare: null });
  assert.deepEqual(r.found.map((f) => f.kind), ["carrier_band_edge", "permanent_discount"]);
  assert.equal(r.found[0].monthlyTypedLow, Math.round(0.96 * 400 * 100) / 100);
  assert.equal(r.found[0].dollarsLow, 0, "typed volume is never bracketed as if it were an estimate");
  assert.equal(r.econ.plan, "grow");
  const h = fees.resultHashShopify({ handle: "shop.example/products/a", price: 32, compareAtPrice: 45, weightOz: 17.2, units: 1, shipCharge: 0, plan: "grow", orders: 400, cogs: 9 });
  const p = new URLSearchParams(h.slice(1));
  assert.equal(p.get("s"), "1"); assert.equal(p.get("pl"), "grow"); assert.equal(p.get("o"), "400"); assert.equal(p.get("u"), null);
});
